//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.31 at 09:57:36 AM PDT 
//


package io.dscope.rosettanet.rnif.v02_00;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.dscope.rosettanet.rnif.v02_00 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.dscope.rosettanet.rnif.v02_00
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StandardName }
     * 
     */
    public StandardName createStandardName() {
        return new StandardName();
    }

    /**
     * Create an instance of {@link StandardVersion }
     * 
     */
    public StandardVersion createStandardVersion() {
        return new StandardVersion();
    }

    /**
     * Create an instance of {@link Preamble }
     * 
     */
    public Preamble createPreamble() {
        return new Preamble();
    }

}
