//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.31 at 09:57:36 AM PDT 
//


package io.dscope.rosettanet.rnif.v02_00;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "standardName",
    "standardVersion"
})
@XmlRootElement(name = "Preamble")
public class Preamble {

    @XmlAttribute(name = "xmlns")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlns;
    @XmlElement(required = true)
    protected StandardName standardName;
    @XmlElement(required = true)
    protected StandardVersion standardVersion;

    /**
     * Gets the value of the xmlns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlns() {
        if (xmlns == null) {
            return "http://www.rosettanet.org/RNIF/V02.00";
        } else {
            return xmlns;
        }
    }

    /**
     * Sets the value of the xmlns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlns(String value) {
        this.xmlns = value;
    }

    /**
     * Gets the value of the standardName property.
     * 
     * @return
     *     possible object is
     *     {@link StandardName }
     *     
     */
    public StandardName getStandardName() {
        return standardName;
    }

    /**
     * Sets the value of the standardName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardName }
     *     
     */
    public void setStandardName(StandardName value) {
        this.standardName = value;
    }

    /**
     * Gets the value of the standardVersion property.
     * 
     * @return
     *     possible object is
     *     {@link StandardVersion }
     *     
     */
    public StandardVersion getStandardVersion() {
        return standardVersion;
    }

    /**
     * Sets the value of the standardVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardVersion }
     *     
     */
    public void setStandardVersion(StandardVersion value) {
        this.standardVersion = value;
    }

}
