//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.31 at 09:57:36 AM PDT 
//


package io.dscope.rosettanet.rnif.v02_00;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalAdministeringAuthorityCode"
})
@XmlRootElement(name = "standardName")
public class StandardName {

    @XmlElement(name = "GlobalAdministeringAuthorityCode", required = true)
    protected String globalAdministeringAuthorityCode;

    /**
     * Gets the value of the globalAdministeringAuthorityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalAdministeringAuthorityCode() {
        return globalAdministeringAuthorityCode;
    }

    /**
     * Sets the value of the globalAdministeringAuthorityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalAdministeringAuthorityCode(String value) {
        this.globalAdministeringAuthorityCode = value;
    }

}
